#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("gnf.Resource", IsApplication=true)]

namespace gnf
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f06000c
			public const int HeaderHeight = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int MainTabHeight = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int MainTotalHeight = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int StressStatusHeaderHeight = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int button_corner_radius = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int button_corner_radius_small = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int button_height = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int button_width = 2131099670;
			
			// aapt resource value: 0x7f060003
			public const int chart_back_line_width = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int chart_bigger_circle_radius = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int chart_cluster_size = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int chart_font_size = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int chart_icon_size = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int chart_line_width = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int chart_shader_y_offset = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int chart_small_circle_radius = 2131099656;
			
			// aapt resource value: 0x7f06001c
			public const int corner_path_effect_size = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int corner_path_effect_size_simple = 2131099677;
			
			// aapt resource value: 0x7f060018
			public const int edittext_width = 2131099672;
			
			// aapt resource value: 0x7f06000b
			public const int ext_chart_line_width = 2131099659;
			
			// aapt resource value: 0x7f06001f
			public const int gauge_height = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int gauge_width = 2131099678;
			
			// aapt resource value: 0x7f060012
			public const int main_chart_bottom_margin = 2131099666;
			
			// aapt resource value: 0x7f06000f
			public const int main_chart_height = 2131099663;
			
			// aapt resource value: 0x7f060021
			public const int main_display_labels_font_size = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int main_display_values_font_size = 2131099680;
			
			// aapt resource value: 0x7f060019
			public const int main_tabs_underline_height = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int main_tabs_underline_margin = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int main_tabs_underline_margin_bottom = 2131099675;
			
			// aapt resource value: 0x7f060011
			public const int main_top_panel_height = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int main_top_panel_width = 2131099664;
			
			// aapt resource value: 0x7f060022
			public const int progress_size = 2131099682;
			
			// aapt resource value: 0x7f06000a
			public const int relax_now_circle = 2131099658;
			
			// aapt resource value: 0x7f060024
			public const int settings_image_margin = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int settings_item_height = 2131099685;
			
			// aapt resource value: 0x7f060023
			public const int settings_margin = 2131099683;
			
			// aapt resource value: 0x7f060000
			public const int test_h = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int test_w = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int gouxuan1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int gouxuan2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int select_device_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int sharp = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001f
			public const int AbsoluteLayout1 = 2131230751;
			
			// aapt resource value: 0x7f080031
			public const int Layout1 = 2131230769;
			
			// aapt resource value: 0x7f080035
			public const int btn_adapter = 2131230773;
			
			// aapt resource value: 0x7f080037
			public const int btn_device = 2131230775;
			
			// aapt resource value: 0x7f080033
			public const int btn_filedemo = 2131230771;
			
			// aapt resource value: 0x7f080005
			public const int btn_finish = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int btn_monitormode = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int btn_selectdevice = 2131230723;
			
			// aapt resource value: 0x7f080021
			public const int btn_start = 2131230753;
			
			// aapt resource value: 0x7f080001
			public const int btn_stop = 2131230721;
			
			// aapt resource value: 0x7f08001c
			public const int chartview = 2131230748;
			
			// aapt resource value: 0x7f08002e
			public const int device_name = 2131230766;
			
			// aapt resource value: 0x7f08002c
			public const int img1 = 2131230764;
			
			// aapt resource value: 0x7f08002d
			public const int img2 = 2131230765;
			
			// aapt resource value: 0x7f08002f
			public const int label_info = 2131230767;
			
			// aapt resource value: 0x7f080006
			public const int layout_grid = 2131230726;
			
			// aapt resource value: 0x7f08001e
			public const int list_select = 2131230750;
			
			// aapt resource value: 0x7f080030
			public const int myButton = 2131230768;
			
			// aapt resource value: 0x7f080000
			public const int tableLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080020
			public const int tableRow1 = 2131230752;
			
			// aapt resource value: 0x7f080022
			public const int tableRow2 = 2131230754;
			
			// aapt resource value: 0x7f080025
			public const int tableRow3 = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int tableRow4 = 2131230758;
			
			// aapt resource value: 0x7f08001d
			public const int textview_log = 2131230749;
			
			// aapt resource value: 0x7f080034
			public const int tv_adapter = 2131230772;
			
			// aapt resource value: 0x7f080018
			public const int tv_attention = 2131230744;
			
			// aapt resource value: 0x7f080017
			public const int tv_attention_label = 2131230743;
			
			// aapt resource value: 0x7f08002a
			public const int tv_badpacket = 2131230762;
			
			// aapt resource value: 0x7f080029
			public const int tv_badpacket_label = 2131230761;
			
			// aapt resource value: 0x7f080024
			public const int tv_delta = 2131230756;
			
			// aapt resource value: 0x7f080023
			public const int tv_delta_label = 2131230755;
			
			// aapt resource value: 0x7f080002
			public const int tv_desc = 2131230722;
			
			// aapt resource value: 0x7f080036
			public const int tv_device = 2131230774;
			
			// aapt resource value: 0x7f080032
			public const int tv_filedemo = 2131230770;
			
			// aapt resource value: 0x7f080012
			public const int tv_highalpha = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int tv_highalpha_label = 2131230737;
			
			// aapt resource value: 0x7f080016
			public const int tv_highbeta = 2131230742;
			
			// aapt resource value: 0x7f080015
			public const int tv_highbeta_label = 2131230741;
			
			// aapt resource value: 0x7f080010
			public const int tv_lowalpha = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int tv_lowalpha_label = 2131230735;
			
			// aapt resource value: 0x7f080014
			public const int tv_lowbeta = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int tv_lowbeta_label = 2131230739;
			
			// aapt resource value: 0x7f08000c
			public const int tv_lowgamma = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int tv_lowgamma_label = 2131230731;
			
			// aapt resource value: 0x7f08001b
			public const int tv_meditation = 2131230747;
			
			// aapt resource value: 0x7f08001a
			public const int tv_meditation_label = 2131230746;
			
			// aapt resource value: 0x7f080028
			public const int tv_middlegamma = 2131230760;
			
			// aapt resource value: 0x7f080027
			public const int tv_middlegamma_label = 2131230759;
			
			// aapt resource value: 0x7f08000a
			public const int tv_power_total = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int tv_power_total_label = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int tv_ps = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int tv_ps_lable = 2131230727;
			
			// aapt resource value: 0x7f080019
			public const int tv_r2r_label = 2131230745;
			
			// aapt resource value: 0x7f08000e
			public const int tv_theta = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int tv_theta_label = 2131230733;
			
			// aapt resource value: 0x7f08002b
			public const int wave_layout = 2131230763;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int bluetoothdevice_view = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int dialog_select_device = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int first_view = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int listitem_device = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Main = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int main_view = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int atype = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int boffline = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int bonline = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int tgam_capture = 2131034115;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
